server:
    port: 8020
    servlet:
        path: /
spring:
    application:
        name: suntion-sms
eureka:
    client:
        service-url:
            defaultZone: http://suntion.cc:8761/eureka
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000