server:
    port: 8030
    servlet:
        path: /
    ssl:
        key-store: classpath:suntion.cc.pfx
        key-store-type: PKCS12
        key-password: cgTv99ha
spring:
    application:
        name: suntion-bankcard
    profiles:
        active: ${active.profile}
eureka:
    client:
        service-url:
            defaultZone: https://localhost:8761/eureka
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 4000
